[package]
name = "portfolio-site-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
glob = "0.3.2"
httparse = "1.10.0"
once_cell = "1.20.3"
regex = "1.11.1"
tokio = { version = "1.43.0", features = ["full"] }
